# Generated by Django 5.1.6 on 2025-04-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Заметка')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст заметки')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заметки')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления заметки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tasks/images', verbose_name='Заставка заметки')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('done', 'Сделано'), ('not_started', 'Не начато')], default='not_started', max_length=20, verbose_name='Статус заметки')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
                'ordering': ('-pub_date',),
            },
        ),
    ]
