# Generated by Django 5.1.6 on 2025-02-20 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заметка')),
                ('text', models.TextField(verbose_name='Текст заметки')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заметки')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления заметки')),
                ('image', models.ImageField(upload_to='tasks/images', verbose_name='Заставка заметки')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор заметки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
                'ordering': ('-pub_date',),
                'constraints': [models.UniqueConstraint(fields=('author', 'name'), name='unique_author_name')],
            },
        ),
    ]
