# Generated by Django 5.1.6 on 2025-05-14 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collaborationrequest',
            name='unique_task_author_collaborator',
        ),
        migrations.AddConstraint(
            model_name='collaborationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending'), ('status', 'accepted'), _connector='OR'), fields=('task', 'author', 'collaborator'), name='unique_task_author_collaborator'),
        ),
    ]
