# Generated by Django 5.1.6 on 2025-05-16 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_collaborationrequest_unique_task_author_collaborator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collaborationrequest',
            name='unique_task_author_collaborator',
        ),
        migrations.RenameField(
            model_name='collaborationrequest',
            old_name='collaborator',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='collaborationrequest',
            old_name='author',
            new_name='sender',
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания запроса'),
        ),
        migrations.AddConstraint(
            model_name='collaborationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending'), ('status', 'accepted'), _connector='OR'), fields=('task', 'sender', 'receiver'), name='unique_task_sender_receiver'),
        ),
    ]
