# Generated by Django 5.1.6 on 2025-02-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default='Безымянная заметка', max_length=255, verbose_name='Заметка'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст заметки'),
        ),
    ]
