# Generated by Django 5.1.6 on 2025-03-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_task_unique_author_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_author_name',
        ),
    ]
