# Generated by Django 5.1.6 on 2025-05-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='Заметка'),
        ),
    ]
