# Generated by Django 5.1.6 on 2025-05-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
