# Generated by Django 5.1.6 on 2025-05-06 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_category_is_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='tasks_collaborators', to=settings.AUTH_USER_MODEL, verbose_name='Коллабораторы'),
        ),
    ]
