# Generated by Django 5.1.6 on 2025-03-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Заметка'),
        ),
    ]
