# Generated by Django 5.1.6 on 2025-05-08 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_remove_task_user_task_collaborators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус запроса')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания запроса на сотрудничество')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_author', to=settings.AUTH_USER_MODEL, verbose_name='Пригласивший')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_receiver', to=settings.AUTH_USER_MODEL, verbose_name='Приглашенный')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Запрос на коллаборацию',
                'verbose_name_plural': 'Запросы на коллаборацию',
                'ordering': ('-request_date',),
                'constraints': [models.UniqueConstraint(fields=('task', 'author', 'collaborator'), name='unique_task_author_collaborator')],
            },
        ),
    ]
