# Generated by Django 5.1.6 on 2025-04-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_category_task_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(default='Без категории', to='tasks.category', verbose_name='Категории'),
        ),
    ]
