# Generated by Django 5.1.6 on 2025-04-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_alter_task_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('in_progress', 'В процессе'), ('done', 'Сделано'), ('not_started', 'Не начато')], max_length=20, unique=True, verbose_name='Статус задачи')),
            ],
            options={
                'verbose_name': 'Статус задачи',
                'verbose_name_plural': 'Статусы задачи',
            },
        ),
    ]
