# Generated by Django 5.1.6 on 2025-04-24 16:55

import django.db.models.deletion
import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default=tasks.models.Status.get_default_status, on_delete=django.db.models.deletion.PROTECT, to='tasks.status', verbose_name='Статус заметки'),
        ),
    ]
