# Generated by Django 5.1.6 on 2025-04-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(to='tasks.category', verbose_name='Категории'),
        ),
    ]
