# Generated by Django 5.1.6 on 2025-05-16 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_friendrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendShipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус запроса')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания запроса')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_receiver', to=settings.AUTH_USER_MODEL, verbose_name='Получатель запроса')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_sender', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель запроса')),
            ],
            options={
                'verbose_name': 'Заявка в друзья',
                'verbose_name_plural': 'Заявки в друзья',
                'ordering': ('-request_date',),
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.AddConstraint(
            model_name='friendshiprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending'), ('status', 'accepted'), _connector='OR'), fields=('sender', 'receiver'), name='unique_sender_receiver'),
        ),
    ]
